services:
  - type: web
    name: agri-genius-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py loaddata agri_app/fixtures/sample_data.json || true
      python manage.py create_admin --username asheesh --email appatel9839@gmail.com --password 'Apatel9839@' || true
      python manage.py collectstatic --noinput
    startCommand: gunicorn agri_project.wsgi:application
